app = "wod-gen"

primary_region = "cdg"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
    dockerfile = "build/Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    soft_limit = 50
    hard_limit = 100

[checks]
    [checks.health]
      type = "http"
      port = 8080
      interval = "10s"
      timeout = "2s"
      grace_period = "15s"
      method = "GET"
      path = "/healthz"
