// Package handlers provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package handlers

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for GenerateWodParamsLevel.
const (
	GenerateWodParamsLevelAdvanced     GenerateWodParamsLevel = "advanced"
	GenerateWodParamsLevelBeginner     GenerateWodParamsLevel = "beginner"
	GenerateWodParamsLevelIntermediate GenerateWodParamsLevel = "intermediate"
)

// Defines values for WodLevel.
const (
	WodLevelAdvanced     WodLevel = "advanced"
	WodLevelBeginner     WodLevel = "beginner"
	WodLevelIntermediate WodLevel = "intermediate"
)

// Block A workout block (movement + params)
type Block struct {
	Name   *string                 `json:"name,omitempty"`
	Params *map[string]interface{} `json:"params,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      int     `json:"code"`
	Message   string  `json:"message"`
	RequestId *string `json:"request_id"`
}

// GenerateWodParams defines model for GenerateWodParams.
type GenerateWodParams struct {
	DurationMin int                    `json:"duration_min" validate:"required,min=15,max=120"`
	Equipment   *[]string              `json:"equipment,omitempty"`
	Level       GenerateWodParamsLevel `json:"level" validate:"required,oneof=beginner intermediate advanced"`
	Seed        *string                `json:"seed,omitempty"`
}

// GenerateWodParamsLevel defines model for GenerateWodParams.Level.
type GenerateWodParamsLevel string

// Wod defines model for Wod.
type Wod struct {
	Blocks           []Block            `json:"blocks"`
	CreatedAt        time.Time          `json:"created_at"`
	DurationMin      int                `json:"duration_min"`
	Equipment        *[]string          `json:"equipment,omitempty"`
	GeneratorVersion string             `json:"generator_version"`
	Id               openapi_types.UUID `json:"id"`
	Level            WodLevel           `json:"level"`
	Seed             string             `json:"seed"`
}

// WodLevel defines model for Wod.Level.
type WodLevel string

// GenerateWodRequest defines model for GenerateWodRequest.
type GenerateWodRequest = GenerateWodParams

// GenerateWodJSONRequestBody defines body for GenerateWod for application/json ContentType.
type GenerateWodJSONRequestBody = GenerateWodParams

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /wod/generate)
	GenerateWod(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GenerateWod operation middleware
func (siw *ServerInterfaceWrapper) GenerateWod(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GenerateWod(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/wod/generate", wrapper.GenerateWod)
}

type GenerateWodRequestObject struct {
	Body *GenerateWodJSONRequestBody
}

type GenerateWodResponseObject interface {
	VisitGenerateWodResponse(w http.ResponseWriter) error
}

type GenerateWod200JSONResponse Wod

func (response GenerateWod200JSONResponse) VisitGenerateWodResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GenerateWod400JSONResponse ErrorResponse

func (response GenerateWod400JSONResponse) VisitGenerateWodResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GenerateWod401JSONResponse ErrorResponse

func (response GenerateWod401JSONResponse) VisitGenerateWodResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GenerateWod403JSONResponse ErrorResponse

func (response GenerateWod403JSONResponse) VisitGenerateWodResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GenerateWod429JSONResponse ErrorResponse

func (response GenerateWod429JSONResponse) VisitGenerateWodResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type GenerateWod500JSONResponse ErrorResponse

func (response GenerateWod500JSONResponse) VisitGenerateWodResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /wod/generate)
	GenerateWod(ctx context.Context, request GenerateWodRequestObject) (GenerateWodResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GenerateWod operation middleware
func (sh *strictHandler) GenerateWod(ctx *gin.Context) {
	var request GenerateWodRequestObject

	var body GenerateWodJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GenerateWod(ctx, request.(GenerateWodRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GenerateWod")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GenerateWodResponseObject); ok {
		if err := validResponse.VisitGenerateWodResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xWTW/jNhD9K8S0hxalbMrZLLACcthF2zSnBkGLAA0WASWOHWZFUiUpfzTwfy+Gkh0r",
	"UreLxSIny/yY997MG42eoHKmcRZtDFA8gce/Wwzxg1Ma08IlWvQy4q1TN90erVbORrTpUTZNrSsZtbPz",
	"x+AsrYXqAY2kp+89LqGA7+bPMPNuN8xPQl9LL02A/X7PEwXtUUERfYu00l+geB9qV32iB4Wh8rohWCjg",
	"Pds4/8m1kZV0gP1g3BoN2sh+Yk2K/SNwaLxr0MdemZUG6Re30jQ1QgE3bgMc4q6hPyF6bVew59AFSFqV",
	"0oQo6+uTUESTP4d5AoMRfYAiF0LsjwFd+YhVhP14hcMv3jt/g6FxNqQQQ6qVU0Oqb4Q4RtE24go9hTEY",
	"gly9UKXtWtZasb60Uwr7rXuthlfLfPlWLtRZNpvNgINt61qWtNNJfhFnULu7jvQzp48TsscOGElXrU/e",
	"ujfaDlNwzsHIrTatgSJfCA5G2/7f+Sg5HLaZk43OiNUKbYbb6GUW5SqhpAzJSDcOErjR9iI/50ZuL/KF",
	"SPJoqzG98Y9M7sC7TcIINSrgULa+QWSld1Kxx9Y0JF5H7PSNst8vSO/ljv7XuMY6IVhScwclrrS1CYH0",
	"eINKE1kOUq2lrVARwGnFB4eGgF+RCWfRLS8OLNhpeHZkkBoV8YWDFBqX0XKWL87g/yzTKefDok8Z59ap",
	"sVVS66enY64/9/rpXiUT+a88yojqXg7LDAuxOM/Eu0y8/SNfFEIUQvwFHJbOGzoKlLYsaoNTLfbSx+Pm",
	"HZjry92y6nrI+fs1+qDdsEtgnU+x6Rr9yLxttZo69pVOHMU5+OLz1U8cTpLPp/3AD4Xu406lYOwZAtN2",
	"6SZmx/UVi471QZBJS+/K6DWukf22826bhbir8TBiCDjqmLKbttnt7z+zywMH9v76CjgciwFils8EZcE1",
	"aGWjoYCzmZgJGkgyPqQqzzdOzQ8MkrNdN2iHVC+PHJnFTcItZUDFnGWVsyF6qW0iSH2RUnalTu5R2/CT",
	"Gb/7rx4ZfAbMJ74BUum6cZUELIT4Zt8FxDLVayie1B5SpFhoqwpDWLZ1ndrgzTckMJzGE1SuhiOVlZTK",
	"RCJ/PRJ/WtnGB+f1P/T2JfCz1wP/1flSK4U2IS/evR7yDfm/1kZHhtsKUXXqz1+3/hG9lTUL6NfoGdIF",
	"OtgNQVoLUNw9QetrKGAuGz1f57D/uP83AAD///4aVOZwCwAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
