name: CI

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          install-mode: binary
          skip-cache: true
          args: --timeout=5m
        continue-on-error: false

      - name: Run tests (-race)
        run: go test ./... -race -count=1 -v

      - name: Build app
        run: go build -trimpath -ldflags="-s -w" -o dist/app ./cmd/wod-gen

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-linux-amd64
          path: dist/app
