name: Security Scan

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  trivy-syft:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - name: Build for scanning
        run: |
          go build -trimpath -ldflags="-s -w" -o dist/app ./cmd/wod-gen

      - name: Build container (local)
        uses: docker/setup-buildx-action@v3
      - name: Docker build
        run: |
          docker build -t local/app:scan -f build/Dockerfile .

      - name: Trivy image scan (SARIF)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: local/app:scan
          format: sarif
          output: trivy-results.sarif
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy SARIF to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

      - name: Generate SBOM (Syft)
        uses: anchore/sbom-action@v0
        with:
          image: local/app:scan
          format: cyclonedx-json
          output-file: sbom-cdx.json

      - name: Upload scan artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            trivy-results.sarif
            sbom-cdx.json
